## Arrays

Ao contrário das listas em Python, o Numpy é restrito à matrizes com dados do mesmo, tipo. Caso os dados sejam de tipos diferentes, como por exemplo contendo números inteiros (integer) e decimais (float), o Numpy transformará os dados integer em float.

In [1]:
# Importando o Numpy
import numpy as np

In [2]:
# Criando uma array unidimensional
array1 = np.array([10, 11, 12, 13])       # Dados integer
array2 = np.array([10.1, 11, 12.3, 13])   # Dados integer e float

print(array1)
print(array2)

[10 11 12 13]
[10.1 11.  12.3 13. ]


In [3]:
# Podemos também, converter uma lista do Python para uma array do Numpy
lista = list(range(0, 15, 2))  # Lista do Python
array = np.array(lista)        # Convertendo a lista em array

print('lista ->', lista)
print('array ->', array)

lista -> [0, 2, 4, 6, 8, 10, 12, 14]
array -> [ 0  2  4  6  8 10 12 14]


In [4]:
# Caso queiramos definir o tipo dos dados do array, podemos utilizar o dtype:
np.array([1, 2, 3], dtype='float32')

array([1., 2., 3.], dtype=float32)

In [5]:
# As arrays também podem possuir muitas dimensões, que são listas aninhadas
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### Criando arrays do zero

In [6]:
# Criando arrays com métodos
array1 = np.zeros((5, 4), dtype=int)  # Utilizando o método zeros
array2 = np.ones(10, dtype=int)   # Utilizando o método ones

print(array1, '<-zeros')
print('ones ->',array2)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]] <-zeros
ones -> [1 1 1 1 1 1 1 1 1 1]


In [7]:
# Criando uma array 4x5, totalmente preenchida por 42
np.full((4, 5), (42))

array([[42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42]])

In [8]:
# Criando uma array de sequencia lienar com arrange
# arange(start, stop, step,, dtype=None)
np.arange(0, 31, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [9]:
# Criando uma array com 6 valores equidistantes entre 0 e 1
# linspace(start, end, number of elements)
np.linspace(0, 1, 6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [10]:
# Criando uma matrix 4x4 uniformemente distribuída com valores entre 0 e 1
np.random.random((4, 4))

array([[0.02619907, 0.60406607, 0.47993589, 0.23628887],
       [0.48340236, 0.22301331, 0.61925133, 0.31162436],
       [0.55335842, 0.02878616, 0.99486009, 0.28121389],
       [0.04576142, 0.31794956, 0.21163929, 0.78929258]])

In [11]:
# Criando uma matriz 4x4 com distribuição Gaussiana de valores aleatórios entre 0 e 1
# normal(loc=0.0, scale=1.0, size=None)
np.random.normal(0, 1, (4, 4))

array([[ 0.25646008,  1.03041491,  1.28257922, -1.159994  ],
       [ 0.44885632,  0.83385505,  0.00558393,  0.96112348],
       [ 1.95868969, -2.27399979,  0.54588789,  0.81241756],
       [-0.38175598,  0.17797978, -0.33040163,  0.059331  ]])

In [12]:
# Criando uma matriz com valores aleatórios inteiros de 0 à 10 com 3 dimensões
array44 = np.random.randint(10, size=(3, 4, 5)); array44

array([[[6, 7, 5, 8, 3],
        [7, 2, 8, 7, 3],
        [7, 3, 4, 4, 6],
        [6, 3, 6, 1, 7]],

       [[3, 3, 3, 6, 7],
        [4, 9, 4, 3, 1],
        [3, 9, 4, 9, 9],
        [3, 3, 3, 9, 2]],

       [[3, 2, 5, 1, 2],
        [8, 3, 2, 6, 1],
        [0, 0, 8, 3, 0],
        [2, 5, 4, 4, 2]]])

In [13]:
# Criando uma matriz identidade 4x4
np.eye(4, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Atributos

In [14]:
# Podemos verificar a dimensão (ndim), o formato (shape) e o tamanho (size)
print(array44.ndim)
print(array44.shape)
print(array44.size)

3
(3, 4, 5)
60


In [15]:
# Podemos também verificar o tipo de dados
arrayN = np.array([4, 8, 15, 16, 23, 42])
arrayL1 = np.array(['Locke', 'Reyes', 'Ford', 'Jarrah', 'Shephard', 'Kwon'])
arrayL2 = np.array(['L', 'O', 'S', 'T'])


print(arrayN.dtype)
print(arrayL1.dtype)
print(arrayL2.dtype)

int32
<U8
<U1


In [16]:
# Também podemos verificar o tamanho dos dados de cada elemento de uma array (em bytes) através do itemsize
# ou verificarmos o tamnaho do array inteiro (em bytes) através do nbytes:
print('Tamanho de cada elemento: ', arrayL1.itemsize, 'bytes')
print('Tamanaho da array inteira:', arrayL1.nbytes, 'bytes')

Tamanho de cada elemento:  32 bytes
Tamanaho da array inteira: 192 bytes


In [17]:
# Caso tenhamos uma array com string representando números, podemos convertê-la usando astype:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

### Tipos de dados no Numpy

As arrays do NumPy contém valores de um único tipo, por isso é importante ter conhecimento de cada um deles e suas limitações.

Devido ao NumPy ter sido contruído em C, os tipos abaixo serão familiaras a usuários que conhecerm C, Fortrar e outras linguagens relacionadas.

| Type  	                           | Type code | Description |
|--------------------------------------|-----------|-------------|
| ``int8, uint8``                      | i1, u1    |Signed and unsigned 8-bit (1 byte) integer types |
| ``int16, uint16`` | i2, u2    |Signed and unsigned 16-bit integer types | 
| ``int32, uint32`` | i4, u4    |Signed and unsigned 32-bit integer types | 
| ``int64, uint64`` | i8, u8    |Signed and unsigned 64-bit integer types | 
| ``float16``       | f2        |Half-precision floating point | 
| ``float32``       | f4 or f   |Standard double-precision floating point; compatible with C double and Python float object |
| ``float64``       | f8 or d   |Extended-precision floating point |
| ``float128``      | f16 or g  |Complex numbers represented by two 32, 64, or 128 floats, respectively | 
| ``complex64, complex128, complex256``| c8, c16, c32| Unsigned integer (0 to 255)| 
| ``bool``    | ? | Boolean type storing True and False values| 
| ``object``    | O | Python object type; a value can be any Python object| 
| ``string_``    | S | Fixed-length ASCII string type (1 byte per character); for example, to create a string dtype with length 10, use 'S10'| 
| ``unicode_``    | U| Fixed-length Unicode type (number of bytes platform specific); same specification semantics as string_ (e.g., 'U10')| 