### Indexing e Slicing

Podemos fatiar as arrays usando o slicing, referenciando pela indexação.

Sintaxe:

    array[linha_ini:linha_fim, coluna_ini:coluna_fim]


**Nota**: Os valores indicados na linha_fim e coluna_fim são exclusive, ou seja, não são trazidos na saída do comando.

**Nota2**:Devemos lembrar que a indexação começa em 0 no Python:

        C      C      C
    [0, 0] [0, 1] [0, 2]
    [1, 0] [1, 1] [1, 2]
    [2, 0] [2, 1] [2, 2]
     L      L      L



In [1]:
import numpy as np

In [2]:
array1 = np.arange(10, 27); array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [3]:
#Criando um array multimensional 4x4
array44 = np.array([range(i, i + 4) for i in [1, 4, 7, 10]]); array44

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

#### Indexing

In [4]:
#Buscando um único elemento de uma array unidimensional
array1[3]

13

In [5]:
# Podemos também buscar vários elementos em uma array, utilizando outra array de indexação:
ind = [4, 6, 9]

array1[ind]

array([14, 16, 19])

In [6]:
#Buscando um único elemento de uma array multidimensional
array44[2]

array([ 7,  8,  9, 10])

In [7]:
# Buscando um único elemento de uma array multidimensional. Nesse caso temos que referecniar linha e coluna 
# Queremos buscar o elemento 7, indexado na linha 2, coluna 0
array44[2, 0]

7

In [8]:
# Também podemos indexar a partir do último elemento, usando índices negativos
array44[-1, 2]

12

#### Slicing

Assim como podemos usar colchetes para acessar elementos individuais de uma array, também podemos usá-los para acessar subarranjos com a notação de fatia, marcada pelo caractere de dois pontos (:).

A sintaxe de fatiamento do NumPy segue a da lista padrão do Python; para acessar uma fatia de um array x, use:

    x[inicio:fim:passo]
    
Se algum desses itens não for especificado, eles serão padronizados para os valores inicio = 0, fim = tamanho da dimensão, passo = 1.

In [9]:
# No exemplo abaixo, vamos selecionar do elemento de índice 5, até o elemento de índice 20, pulando de 2 em 2
array1[5:17:2]    # Selecionado índice de 5 à 29, poulando de 2 em 2

array([15, 17, 19, 21, 23, 25])

In [10]:
# Podemos trazer a array de maneira inversa
array1[::-1]

array([26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [11]:
# Buscando somente a coluna 0
array44[:, :1] # Como não especificamos as linhas, o NumPy atribuírá início=0, fim =4, ou seja, todas as linhas

array([[ 1],
       [ 4],
       [ 7],
       [10]])

In [12]:
# Trazendo a linha 1
array44[:1]

array([[1, 2, 3, 4]])

In [13]:
# Trazendo as linhas e colunas 2 e 3
array44[1:3, 1:3]

array([[5, 6],
       [8, 9]])

#### Atribuindo condições à um slicing

In [14]:
#Podemos utilizizar condições para retornar os dados dentro de uma array.
print(array1, 'Valores originais da array')

print(array1[array1 > 23], 'Trazendo valores acima de 23 com o operador ">"')
print(array1[array1 %2 != 0], 'Trazendo valores utilizando operadores e condições')

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26] Valores originais da array
[24 25 26] Trazendo valores acima de 23 com o operador ">"
[11 13 15 17 19 21 23 25] Trazendo valores utilizando operadores e condições


#### Modificando uma array

Quando atribuímos uma array a uma nova subarray utilizando o sinal ``=``, as duas continuam ligadas. Com isso se modificarmos uma a outra também será modificada. Esse comportamento padrão é realmente útil: significa que quando trabalhamos com grandes conjuntos de dados, podemos acessar e processar partes desses conjuntos sem a necessidade de copiar o buffer de dados subjacente.

Devemos utilizar a função ``copy()`` caso se queira manter os dados da array original, sendo modificada somente a cópia.

In [15]:
# Podemos utilizar o slicing para modificar o elemento de uma matriz
array44_2 = array44.copy()
array44_2[1, 2] = 15   # Substituiremos o elemento de índice 1, 2 (linha 2, coluna 3) por 15
array44_2

array([[ 1,  2,  3,  4],
       [ 4,  5, 15,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [16]:
# Ou se preferirmos, podemos alterar um intervalo
array44_2[:, 2:] = 15   # Todas as linhas das colunas de índice 2 em diante receberão o valor 15
array44_2

array([[ 1,  2, 15, 15],
       [ 4,  5, 15, 15],
       [ 7,  8, 15, 15],
       [10, 11, 15, 15]])