### Operações com arrays

As arrays (ou matrizes) são importantes porque permitem que você expresse operações em lote em dados sem utilizar loop for. Os usuários do NumPy chamam isso de vetorização. Qualquer operação aritmética entre matrizes de tamanho igual são faceis de aplicar.

In [1]:
# Carregando o NumPy
import numpy as np

In [2]:
# Criando uma matriz
array1 = np.array([[1., 2., 3.], [4., 5., 6.]]); array1

array([[1., 2., 3.],
       [4., 5., 6.]])

In [3]:
# Multiplicando seus elementos entre si
array1 * array1

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [4]:
# Subtraindo seus elementos
array1 - array1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
# Aplicando o inverso de cada elemento
1 / array1

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [6]:
# Criando uma array de 0 a 30 e multiplicando cada um dos elementos por 5
np.arange(0, 30) * 5

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

In [7]:
# Comparando arrays
array1 = np.arange(0, 9)    # array de 0 a 9
array2 = np.arange(10, 19)  # array de 10 a 19

array1 < array2  # Verificando se os elementos da array1 são menores que da array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])