### Arrays - Transposição, reshaping e concatenate

In [1]:
# Importando o módulo NumPy
import numpy as np

#### Transposição
A transposição de uma matriz é tranformar suas colunas em linhas e suas linhas em colunas. Esse processo também é conhecido como "pivotar" os dados.

In [2]:
# Gerando uma array 4x3
array4x3 = np.array([range(i, i + 3) for i in [1, 4, 7, 10]]); array4x3

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
# Podemos executar a matriz transposta pelo comando T do Python, transformando-a em 3x4
array4x3.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [4]:
# Podemos também executar a matriz transposta pelo comando transpose do NumPy, obtendo o mesmo resultado
array4x3.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

#### Reshaping

Podemos utilizar a função ``reshape()`` para remodelar os dados. O único cuidado que devemos ter é de que os dados originais tenham o mesmo tamanho da array desejada.

In [5]:
# Criando uma lista
lista = list(range(9)); lista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [6]:
# Executando reshaping
array1 = np.array(lista) # Atribuindo a lista à uma array

array1.reshape(3, 3) # Remodelando para uma matrix 3x3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# Podemos executar o reshaping de uma maneira direta
X = np.arange(12).reshape((3, 4))
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [8]:
# Podemos utilizar o valor -1, quando não quisermos informar uma das dimensões (linha, coluna).
array4x3.reshape(-1, 2)
# O Numpy organizará a quantidade de linhas necessárias para atender às duas colunas solicidadas

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [9]:
# Podemos também transformar uma matriz em um vetor com a função "ravel"
array4x3.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

#### Conctenate

Podemos concatenar uma ou mais arrays através da função concatenate

In [10]:
x = np.array([[1, 2, 3], [3, 4, 5]])
y = np.array([[6, 7, 8], [8, 9, 10]])
z = np.array([[11, 12, 13], [13, 14, 15]])

np.concatenate([x, y, z])

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 8,  9, 10],
       [11, 12, 13],
       [13, 14, 15]])